### ISSUE TITLE
Startup issue with rqt_bag

### ISSUE THREAD

**Issue by mikepurvis** [mikepurvis/ros-install-osx#89]
Upon launch, there's an error:

```
$ rqt_bag robot_2017-10-04-23-02-30_20.bag
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/ros/lunar/lib/python2.7/site-packages/rqt_bag/bag.py", line 61, in load_bags
    self._widget.load_bag(bagfile)
  File "/opt/ros/lunar/lib/python2.7/site-packages/rqt_bag/bag_widget.py", line 267, in load_bag
    qInfo("Loading '%s'..." % filename)
NameError: global name 'qInfo' is not defined
```

If the two instances of `qInfo` in that file are commented out, it's able to launch fine. Looks like a QT5 thing:

http://doc.qt.io/qt-5/qtglobal.html#qInfo

**Comment by mikepurvis** [comment]
Fixed upstream.
